baseurl = "/"
languageCode = "en-us"
title = "EDLD 654 Final Project"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/kgrove10/EDLD654_blog"
[[menu.main]]
    name = "Kaggle"
    url = "https://www.kaggle.com/c/edld-654-fall-2020"

[params]
    description = "Fall 2020 EDLD 654 Final Project"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    
    [params.logo]
    url = "aokthick.png"
    width = 30
    height = 50
    alt = "Logo"


